image: node:12
deploy:
  script:
    - npm install
    - npm run build
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" > /dev/null
    - unzip awscliv2.zip > /dev/null
    - ./aws/install > /dev/null
    - /usr/local/bin/aws s3 sync --acl=public-read public s3://events-decentraland-io-contentbucket-0dce4ae/
