name: Deploy Master

on:
  push:
    branches:
      - master

jobs:

  build-push:
    runs-on: ubuntu-20.04
    outputs:
      registry-path: ${{ steps.push-to-quay.outputs.registry-path }}
      registry-paths: ${{ steps.push-to-quay.outputs.registry-paths }}

    steps:
      - uses: actions/checkout@v3

      - name: reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: installing
        run: npm install

      - name: linters
        uses: wearerequired/lint-action@v2
        with:
          prettier: true
          prettier_extensions: ts,tsx,js,jsx,json,md,mdx,css
          continue_on_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: testing
        run: npm test -- --coverage

      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup envs
        run: touch .env

      - name: build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: events
          tags: ${{ github.sha }} ${{ github.ref_name == 'master' && 'latest' || github.ref_name }}
          dockerfiles: |
            ./Dockerfile

      - name: push to quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/decentraland
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Print image url
        run: |
          echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

  deployment:
    needs: [build-push]
    name: "Deploy to: dev"
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        id: deploy
        uses: decentraland/dcl-deploy-action@main
        with:
          dockerImage: "${{ needs.build-push.outputs.registry-path }}"
          serviceName: events2
          env: dev
          token: ${{ secrets.GITHUB_TOKEN }}